# Generated by Django 3.1.7 on 2021-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('content', models.TextField(blank=True, null=True)),
                ('simple_post', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=122)),
                ('post_url', models.CharField(max_length=122)),
                ('thumbnail_img', models.ImageField(upload_to='blog_contents')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
