# Generated by Django 3.1.7 on 2021-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_contents'),
        ),
    ]
