# Generated by Django 3.1.7 on 2021-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='InstaImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instaImage', models.ImageField(upload_to='pages')),
            ],
        ),
        migrations.CreateModel(
            name='LogoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoImage', models.ImageField(upload_to='pages')),
            ],
        ),
        migrations.CreateModel(
            name='ProductID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImage', models.ImageField(upload_to='pages')),
            ],
        ),
        migrations.CreateModel(
            name='UpSliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upsliderImage', models.ImageField(upload_to='pages')),
            ],
        ),
    ]
